server:
  type: simple
  applicationContextPath: /academic
  adminContextPath: /admin
  connector:
    type: http
    port: 8080

database:
  driverClass: org.h2.Driver
  user: sa
  password: sa
  url: jdbc:h2:~/home/arthur/eclipse-workspace/academico/academicdb
  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.H2Dialect
    hibernate.hbm2ddl.auto: update
    hibernate.current_session_context_class: thread

logging:
  level: INFO
  loggers:
    br.ufal.ic.academico: DEBUG
    org.hibernate.SQL:
      level: DEBUG
